// This file is auto-generated by scripts/generate-gallery.js
// Do not edit this file manually. Run: node scripts/generate-gallery.js

export interface GalleryItem {
  type: "image" | "video";
  src: string;
  caption: string;
  category: "Photos" | "Videos";
}

export const galleryCategories = ["All", "Photos", "Videos"] as const;

export type GalleryCategory = typeof galleryCategories[number];

export const galleryItems: GalleryItem[] = [
  {
    "type": "image",
    "src": "/gallery/1.jpg",
    "caption": "Pranil Highlight - Photo 1",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/2.jpg",
    "caption": "Pranil Highlight - Photo 2",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/2ae0a1ba-fa82-41a8-bcb6-fa8352359d6d.jpg",
    "caption": "Pranil Moment - Photo 3",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/7af16406-404b-4e79-8fc2-02b3091dd6ac.jpg",
    "caption": "Pranil Moment - Photo 4",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/9c99e8b9-2216-4b62-99ef-c15aef8f7d42.jpg",
    "caption": "Pranil Moment - Photo 5",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/992ba7f0-19e7-41e8-b98b-712a8007f620.jpg",
    "caption": "Pranil Moment - Photo 6",
    "category": "Photos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_122721.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_122739.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_140725.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_140755.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_141205.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_141400.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_142004.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_142026.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_142231.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_142520.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_142646.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_142850.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_143021.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_144005.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_145228.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20241214_145556.mp4",
    "caption": "Event Video Highlight - Dec 14, 2024",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094023.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094049.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094108.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094130.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094226.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094244.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094249.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094309.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094421.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094447.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094517.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094548.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094605.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094640.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094733.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094825.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_094935.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095007.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095032.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095112.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095144.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095225.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095309.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095415.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095439.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095511.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095637.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095654.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095710.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095749.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250111_095810.mp4",
    "caption": "Event Video Highlight - Jan 11, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250122_173953.mp4",
    "caption": "Event Video Highlight - Jan 22, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250122_174025.mp4",
    "caption": "Event Video Highlight - Jan 22, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250122_174038.mp4",
    "caption": "Event Video Highlight - Jan 22, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250201_115626.mp4",
    "caption": "Event Video Highlight - Feb 1, 2025",
    "category": "Videos"
  },
  {
    "type": "image",
    "src": "/gallery/20250201_115732.jpg",
    "caption": "Event Photo - Feb 1, 2025",
    "category": "Photos"
  },
  {
    "type": "video",
    "src": "/gallery/20250213_183031.mp4",
    "caption": "Event Video Highlight - Feb 13, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250215_165730.mp4",
    "caption": "Event Video Highlight - Feb 15, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250215_165739.mp4",
    "caption": "Event Video Highlight - Feb 15, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250215_170153.mp4",
    "caption": "Event Video Highlight - Feb 15, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250215_170530.mp4",
    "caption": "Event Video Highlight - Feb 15, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250215_170756.mp4",
    "caption": "Event Video Highlight - Feb 15, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250215_170943.mp4",
    "caption": "Event Video Highlight - Feb 15, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250215_171135.mp4",
    "caption": "Event Video Highlight - Feb 15, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250215_171227.mp4",
    "caption": "Event Video Highlight - Feb 15, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250215_172536.mp4",
    "caption": "Event Video Highlight - Feb 15, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250215_175750.mp4",
    "caption": "Event Video Highlight - Feb 15, 2025",
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/gallery/20250215_181249.mp4",
    "caption": "Event Video Highlight - Feb 15, 2025",
    "category": "Videos"
  },
  {
    "type": "image",
    "src": "/gallery/20250527_142854.jpg",
    "caption": "Event Photo - May 27, 2025",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/unnamed (9).webp",
    "caption": "Unnamed (9)",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/unnamed (10).webp",
    "caption": "Unnamed (10)",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/unnamed (14).webp",
    "caption": "Unnamed (14)",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/WhatsApp Image 2026-05-20 at 11.41.11 AM.jpeg",
    "caption": "Group Highlight - May 20, 2026",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/WhatsApp Image 2026-05-20 at 11.41.16 AM.jpeg",
    "caption": "Group Highlight - May 20, 2026",
    "category": "Photos"
  },
  {
    "type": "image",
    "src": "/gallery/WhatsApp Image 2026-05-23 at 2.47.43 PM.jpeg",
    "caption": "Group Highlight - May 23, 2026",
    "category": "Photos"
  }
];
