const fs = require("fs");
const path = require("path");

// Configure paths
const GALLERY_DIR = path.join(__dirname, "../public/gallery");
const DATA_FILE = path.join(__dirname, "../src/lib/gallery-data.ts");

// Allowed categories under new requirement
const CATEGORIES = ["All", "Photos", "Videos"];

// Ensure gallery folder exists
if (!fs.existsSync(GALLERY_DIR)) {
  fs.mkdirSync(GALLERY_DIR, { recursive: true });
}

// Supported file extensions
const IMAGE_EXTS = [".jpg", ".jpeg", ".png", ".webp", ".gif", ".tiff", ".bmp"];
const VIDEO_EXTS = [".mp4", ".webm", ".ogg", ".mov", ".mkv"];

const MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function formatDate(year, monthStr, dayStr) {
  const month = parseInt(monthStr, 10);
  const day = parseInt(dayStr, 10);
  if (month >= 1 && month <= 12) {
    return `${MONTH_NAMES[month - 1]} ${day}, ${year}`;
  }
  return null;
}

function parseFilename(filename, photoIndex, videoIndex) {
  const ext = path.extname(filename).toLowerCase();
  const baseName = path.basename(filename, ext);
  
  let type = "image";
  if (VIDEO_EXTS.includes(ext)) {
    type = "video";
  } else if (!IMAGE_EXTS.includes(ext)) {
    return null; // Unsupported file type
  }

  // Set category strictly under user requirements: "Photos" or "Videos"
  const category = type === "image" ? "Photos" : "Videos";

  let caption = "";

  // 1. Detect standard camera date format (e.g., 20241214_122721)
  const cameraDateMatch = baseName.match(/^(20\d{2})(\d{2})(\d{2})_\d+/);
  if (cameraDateMatch) {
    const dateStr = formatDate(cameraDateMatch[1], cameraDateMatch[2], cameraDateMatch[3]);
    if (dateStr) {
      caption = `${type === "image" ? "Event Photo" : "Event Video Highlight"} - ${dateStr}`;
    }
  }

  // 2. Detect WhatsApp date format (e.g., WhatsApp Image 2026-05-20 at 11.41.11 AM)
  if (!caption) {
    const waMatch = baseName.match(/(?:WhatsApp Image|WhatsApp Video)\s(20\d{2})-(\d{2})-(\d{2})/);
    if (waMatch) {
      const dateStr = formatDate(waMatch[1], waMatch[2], waMatch[3]);
      if (dateStr) {
        caption = `Group Highlight - ${dateStr}`;
      }
    }
  }

  // 3. Simple numeric filename fallback (e.g., 1.jpg)
  if (!caption) {
    const numOnlyMatch = baseName.match(/^(\d+)$/);
    if (numOnlyMatch) {
      caption = `Pranil Highlight - Photo ${numOnlyMatch[1]}`;
    }
  }

  // 4. Default clean fallback for other names
  if (!caption) {
    // Replace hyphens, underscores and hashes
    let cleanName = baseName.replace(/[-_#]/g, " ").trim();
    // Capitalize words
    cleanName = cleanName.replace(/\b\w/g, c => c.toUpperCase());
    
    // If it's a random hash UUID (e.g. 2ae0a1ba-fa82...)
    if (baseName.length > 20 && baseName.includes("-")) {
      caption = `Pranil Moment - Photo ${photoIndex}`;
    } else {
      caption = cleanName;
    }
  }

  return {
    type,
    src: `/gallery/${filename}`,
    caption,
    category
  };
}

function generateGalleryData() {
  console.log("Scanning public/gallery for media...");
  
  const files = fs.readdirSync(GALLERY_DIR);
  const items = [];
  
  let photoIndex = 1;
  let videoIndex = 1;

  // Sort files to keep them grouped nicely
  files.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

  files.forEach(file => {
    // Skip hidden files
    if (file.startsWith(".")) return;

    // Skip duplicates (files ending with "(1)" or containing " (1)")
    const ext = path.extname(file).toLowerCase();
    const baseName = path.basename(file, ext);
    if (baseName.endsWith(" (1)") || baseName.includes(" (1)")) {
      console.log(`Skipping duplicate file: ${file}`);
      return;
    }
    
    const item = parseFilename(file, photoIndex, videoIndex);
    if (item) {
      items.push(item);
      if (item.type === "image") {
        photoIndex++;
      } else {
        videoIndex++;
      }
    }
  });

  const content = `// This file is auto-generated by scripts/generate-gallery.js
// Do not edit this file manually. Run: node scripts/generate-gallery.js

export interface GalleryItem {
  type: "image" | "video";
  src: string;
  caption: string;
  category: "Photos" | "Videos";
}

export const galleryCategories = ["All", "Photos", "Videos"] as const;

export type GalleryCategory = typeof galleryCategories[number];

export const galleryItems: GalleryItem[] = ${JSON.stringify(items, null, 2)};
`;

  fs.writeFileSync(DATA_FILE, content, "utf8");
  console.log(`\n\x1b[32m✔ Successfully generated data for ${items.length} items (skipped duplicates)!\x1b[0m`);
  console.log(`\x1b[34mData written to: ${DATA_FILE}\x1b[0m\n`);
}

generateGalleryData();
